import java.util.HashMap;
import java.util.*;

/**
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 *
 * Created by Mellon on 8/28/16.
 */
public class FindtheDifference {
    public static char findTheDifferenceSort(String s, String t) {
        char[] s_charArray = s.toCharArray();
        char[] t_charArray = t.toCharArray();
        Arrays.sort(s_charArray);
        Arrays.sort(t_charArray);
        int i=0;
        int j=0;
        while(i<s_charArray.length){
            if(s_charArray[i]!=t_charArray[j])
                return t_charArray[j];
            i++;j++;
        }
        return t_charArray[t.length()-1];
    }

    public static char findTheDifferenceXOR(String s, String t) {
        int n = t.length();
        char c = t.charAt(n - 1);
        for (int i = 0; i < n - 1; ++i) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }


    public static char findTheDifference(String s, String t) {
        HashMap<Character, Integer> map = new HashMap<>();
        char[] chars = s.toCharArray();
        for(int i=0;i<chars.length;i++){
            if(map.containsKey(chars[i])){
                map.put(chars[i], map.get(chars[i])+1);
            }else{
                map.put(chars[i], 1);
            }
        }

        HashMap<Character, Integer> map2 = new HashMap<>();
        char[] chars2 = t.toCharArray();
        for(int i=0;i<chars2.length;i++){
            if(map2.containsKey(chars2[i])){
                map2.put(chars2[i], map2.get(chars2[i])+1);
            }else{
                map2.put(chars2[i], 1);
            }
        }

        for (Map.Entry<Character, Integer> entry : map2.entrySet()) {
            if(!map.containsKey(entry.getKey())){
                return entry.getKey();
            }else {
                if(map.get(entry.getKey())!=entry.getValue())
                    return entry.getKey();
            }
        }
        return ' ';
    }

    public static void main(String[] args){
//        String s = "ihwrdisrhgxwbfevrxbtzgsywhnzleueadikniwyuasflpsviobwvsmydmyzppqjlmzakpbnouyttdigkcdzypvcqxbttmblttehgjlnpjwpzoprntifysfatjboasottnkpyyvmdcafpjicfpgmbwqdsaxdmmdmupnwhkpxixpdwmczntqtushemvavofszomtsrafzmxctpidjadwcwggdbyliqmcvuwscryfsvlvfrhfphmxvcnytbctomicwdwjjmdhmcqtnlqgixxdyjydhwnftkobotbhsgykawhtvnkxoykwkgvtqioqoiilergxlpuujabiug";
//        String t = "gyptmtjntxlusjhbzkbgowslthwtytdnflsyfsgfytzrodatykdyvgsmvxsuemijitvodmwrrqmcabhwzyoouorfckhisjpduoxvtmttzvwmicdxsovsabmpcpppzycuwbmpihmxadmvkkwerimhgwdwdtvqwbwtetppkpkbcaifuqbenagycdqatklciaczcpglxmvfaqnwpnssdmnhcmifeyndzttvypwlgpttvhswoiijybchbvzklgngqziyaczowgwiufqyhxxdqjrxolddgnmriijopdsikqwtyhplhubrljfjanexxyfvjmudxsomnfbafntpib";
        String s = "123";
        String t = "1232";
//        char res = findTheDifferenceSort(s, t);
        char res = findTheDifferenceXOR(s, t);
        System.out.print(res);
    }
}
